//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBuzz.Repository.DbContext
{
    using FilmBuzz.Common.Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmBuzzDbContext : DbContext
    {
        public FilmBuzzDbContext()
            : base("name=FilmBuzzDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ACTORS> TBL_ACTORS { get; set; }
        public virtual DbSet<TBL_MOVIES> TBL_MOVIES { get; set; }
        public virtual DbSet<TBL_PRODUCERS> TBL_PRODUCERS { get; set; }
    }
}
