//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBuzz.Repository.DbContext
{
    using System;
    using System.Collections.Generic;
    
    //public partial class TBL_MOVIES
    //{
    //    public int MovieId { get; set; }
    //    public string Name { get; set; }
    //    public Nullable<int> YearofRelease { get; set; }
    //    public string Plot { get; set; }
    //    public byte[] Poster { get; set; }
    //    public Nullable<int> ActorId { get; set; }
    //    public int ProducerId { get; set; }
    
    //    public virtual TBL_ACTORS TBL_ACTORS { get; set; }
    //    public virtual TBL_PRODUCERS TBL_PRODUCERS { get; set; }
    //}
}
