//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBuzz.Repository.DbContext
{
    using System;
    using System.Collections.Generic;
    
    //public partial class TBL_ACTORS
    //{
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    //    public TBL_ACTORS()
    //    {
    //        this.TBL_MOVIES = new HashSet<TBL_MOVIES>();
    //    }
    
    //    public int ActorId { get; set; }
    //    public string Name { get; set; }
    //    public string Sex { get; set; }
    //    public Nullable<System.DateTime> DOB { get; set; }
    //    public string Bio { get; set; }
    
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    //    public virtual ICollection<TBL_MOVIES> TBL_MOVIES { get; set; }
    //}
}
